<?php
$brandCatalog = [
    'jbl' => [
        'name' => 'JBL',
        'logo' => 'JBL',
        'logo_file' => 'img/demo/brands/jbl.svg',
        'eyebrow' => 'Audio que te mueve',
        'tagline' => 'Parlantes y audifonos con energia, color y potencia para casa, oficina y salidas.',
        'accent' => '#ff6b1a',
        'accent_soft' => '#ffe5d6',
        'starting_price' => 'S/ 59',
        'categories' => ['Parlantes portatiles', 'Audifonos grandes', 'Audifonos pequenos'],
    ],
    'nco' => [
        'name' => 'NCO',
        'logo' => 'nco',
        'logo_file' => 'img/demo/brands/nco.svg',
        'eyebrow' => 'Accesorios con estilo',
        'tagline' => 'Diseno limpio para proteccion, carga y accesorios que combinan con tu ecosistema.',
        'accent' => '#f59e0b',
        'accent_soft' => '#fef3c7',
        'starting_price' => 'S/ 49',
        'categories' => ['Cases', 'Cargadores', 'Power banks'],
    ],
    'bose' => [
        'name' => 'Bose',
        'logo' => 'BOSE',
        'logo_file' => 'img/demo/brands/bose.svg',
        'eyebrow' => 'Sonido premium',
        'tagline' => 'Audio de alta fidelidad para musica, trabajo y cancelacion de ruido de nivel superior.',
        'accent' => '#111827',
        'accent_soft' => '#e5e7eb',
        'starting_price' => 'S/ 699',
        'categories' => ['Audifonos premium', 'Parlantes inteligentes', 'Soundbars'],
    ],
    'belkin' => [
        'name' => 'Belkin',
        'logo' => 'belkin',
        'logo_file' => 'img/demo/brands/belkin.svg',
        'eyebrow' => 'Carga y conectividad',
        'tagline' => 'Soluciones confiables para carga rapida, docks, cables y accesorios para escritorio.',
        'accent' => '#111827',
        'accent_soft' => '#dbeafe',
        'starting_price' => 'S/ 59',
        'categories' => ['Cables', 'Cargadores', 'Docks'],
    ],
    'marshall' => [
        'name' => 'Marshall',
        'logo' => 'Marshall',
        'logo_file' => 'img/demo/brands/marshall.svg',
        'eyebrow' => 'Diseno iconico',
        'tagline' => 'Parlantes y audifonos con look clasico, presencia fuerte y sonido muy marcado.',
        'accent' => '#1f2937',
        'accent_soft' => '#f3f4f6',
        'starting_price' => 'S/ 449',
        'categories' => ['Parlantes bluetooth', 'Audifonos', 'Home audio'],
    ],
    'zagg' => [
        'name' => 'Zagg',
        'logo' => 'ZAGG',
        'logo_file' => 'img/demo/brands/zagg.svg',
        'eyebrow' => 'Proteccion avanzada',
        'tagline' => 'Protectores, teclados y accesorios para iPhone y iPad con enfoque en productividad.',
        'accent' => '#ef5a2a',
        'accent_soft' => '#ffedd5',
        'starting_price' => 'S/ 59',
        'categories' => ['Protectores', 'Teclados', 'Cases'],
    ],
];

$brandProducts = [
    [
        'sku' => 'jbl-go4-black',
        'brand' => 'jbl',
        'name' => 'Parlante JBL Go 4 Bluetooth - Negro',
        'image' => 'img/demo/brand-products/jbl/jbl-go4-black.svg',
        'price' => 'S/ 189',
        'old_price' => 'S/ 219',
        'badge' => 'Oferta',
        'rating' => '5.0',
        'blurb' => 'Compacto, potente y perfecto para llevar musica a cualquier lado.',
        'description' => 'El JBL Go 4 combina un cuerpo compacto con sonido sorprendentemente amplio. Es ideal para escritorios, habitaciones y salidas rapidas donde necesitas un parlante pequeno pero con presencia.',
        'features' => ['Bluetooth de conexion rapida', 'Bateria para uso diario', 'Formato compacto y ligero', 'Acabado resistente para movilidad'],
        'art' => 'speaker',
        'tone' => 'orange',
    ],
    [
        'sku' => 'jbl-tune-770nc',
        'brand' => 'jbl',
        'name' => 'JBL Tune 770NC',
        'image' => 'img/demo/brand-products/jbl/jbl-tune-770nc.svg',
        'price' => 'S/ 329',
        'old_price' => '',
        'badge' => 'Top',
        'rating' => '5.0',
        'blurb' => 'Audifonos over-ear comodos con cancelacion de ruido para trabajar y viajar.',
        'description' => 'Pensado para quien necesita concentracion y comodidad durante varias horas. Su estilo sobrio lo vuelve una opcion facil de recomendar en tienda.',
        'features' => ['Cancelacion de ruido', 'Ajuste comodo over-ear', 'Audio balanceado para voz y musica', 'Ideal para home office'],
        'art' => 'headphones',
        'tone' => 'dark',
    ],
    [
        'sku' => 'jbl-charge-5',
        'brand' => 'jbl',
        'name' => 'JBL Charge 5',
        'image' => 'img/demo/brand-products/jbl/jbl-charge-5.svg',
        'price' => 'S/ 599',
        'old_price' => '',
        'badge' => '',
        'rating' => '4.9',
        'blurb' => 'Parlante cilindrico con mas cuerpo y autonomia para reuniones y terraza.',
        'description' => 'Una opcion muy fuerte para quien quiere subir de nivel desde un parlante compacto a uno con mas presencia y bateria.',
        'features' => ['Mayor volumen y graves', 'Cuerpo portable', 'Diseno robusto', 'Pensado para ambientes abiertos'],
        'art' => 'bar-speaker',
        'tone' => 'blue',
    ],
    [
        'sku' => 'nco-crystal-case',
        'brand' => 'nco',
        'name' => 'NCO Crystal Case para iPhone',
        'image' => 'img/demo/brand-products/nco/nco-crystal-case.svg',
        'price' => 'S/ 59',
        'old_price' => '',
        'badge' => 'Nuevo',
        'rating' => '4.8',
        'blurb' => 'Case transparente con bordes reforzados para proteger sin esconder el color del equipo.',
        'description' => 'Una funda pensada para quienes quieren proteccion limpia, buen agarre y visual premium sin cargar el diseno del iPhone.',
        'features' => ['Transparencia clara', 'Bordes reforzados', 'Compatible con carga inalambrica', 'Ajuste preciso para botones'],
        'art' => 'case',
        'tone' => 'gold',
    ],
    [
        'sku' => 'nco-powerbank-slim',
        'brand' => 'nco',
        'name' => 'NCO Power Bank Slim',
        'image' => 'img/demo/brand-products/nco/nco-powerbank-slim.svg',
        'price' => 'S/ 119',
        'old_price' => 'S/ 139',
        'badge' => 'Oferta',
        'rating' => '4.7',
        'blurb' => 'Bateria externa delgada para iPhone, AirPods y accesorios del dia a dia.',
        'description' => 'Ideal para llevar en mochila o bolso sin sumar peso excesivo, manteniendo buena autonomia para jornadas largas.',
        'features' => ['Formato delgado', 'USB-C de carga rapida', 'Indicador de bateria', 'Compatible con multiples dispositivos'],
        'art' => 'powerbank',
        'tone' => 'blue',
    ],
    [
        'sku' => 'nco-charge-stand',
        'brand' => 'nco',
        'name' => 'NCO Base de Carga 3 en 1',
        'image' => 'img/demo/brand-products/nco/nco-charge-stand.svg',
        'price' => 'S/ 179',
        'old_price' => '',
        'badge' => '',
        'rating' => '4.9',
        'blurb' => 'Base para iPhone, Apple Watch y AirPods en un solo punto de carga.',
        'description' => 'Perfecta para mesa de noche o escritorio, ayudando a ordenar el ecosistema con una presentacion mucho mas limpia.',
        'features' => ['Carga simultanea', 'Formato de escritorio', 'Ideal para ecosistema Apple', 'Diseno limpio y moderno'],
        'art' => 'dock',
        'tone' => 'silver',
    ],
    [
        'sku' => 'bose-qc-ultra',
        'brand' => 'bose',
        'name' => 'Bose QuietComfort Ultra',
        'image' => 'img/demo/brand-products/bose/bose-qc-ultra.svg',
        'price' => 'S/ 1,699',
        'old_price' => '',
        'badge' => 'Premium',
        'rating' => '5.0',
        'blurb' => 'Audifonos premium para quienes quieren silencio, comodidad y audio serio.',
        'description' => 'Una referencia clara cuando el cliente busca subir a un nivel mas alto de comodidad y cancelacion de ruido.',
        'features' => ['Cancelacion de ruido premium', 'Construccion ligera', 'Ideal para viajes y oficina', 'Acabado elegante'],
        'art' => 'headphones',
        'tone' => 'dark',
    ],
    [
        'sku' => 'bose-portable-speaker',
        'brand' => 'bose',
        'name' => 'Bose Portable Smart Speaker',
        'image' => 'img/demo/brand-products/bose/bose-portable-speaker.svg',
        'price' => 'S/ 1,299',
        'old_price' => '',
        'badge' => '',
        'rating' => '4.9',
        'blurb' => 'Parlante premium para casa con look limpio y presencia elegante.',
        'description' => 'Muy buen producto para living, oficina premium o clientes que valoran sonido de calidad con una estetica mas discreta.',
        'features' => ['Sonido amplio', 'Formato elegante', 'Uso domestico premium', 'Facil de integrar al espacio'],
        'art' => 'speaker',
        'tone' => 'silver',
    ],
    [
        'sku' => 'bose-soundbar-600',
        'brand' => 'bose',
        'name' => 'Bose Smart Soundbar 600',
        'image' => 'img/demo/brand-products/bose/bose-soundbar-600.svg',
        'price' => 'S/ 1,899',
        'old_price' => '',
        'badge' => '',
        'rating' => '4.8',
        'blurb' => 'Soundbar para televisores y espacios de entretenimiento con look minimalista.',
        'description' => 'Perfecta para complementar televisores y zonas de entretenimiento que ya estas promocionando en la pagina.',
        'features' => ['Perfil delgado', 'Pensada para TV', 'Acabado minimalista', 'Mejora clara de audio en casa'],
        'art' => 'soundbar',
        'tone' => 'dark',
    ],
    [
        'sku' => 'belkin-boostcharge-pro',
        'brand' => 'belkin',
        'name' => 'Belkin BoostCharge Pro 3 en 1',
        'image' => 'img/demo/brand-products/belkin/belkin-boostcharge-pro.svg',
        'price' => 'S/ 649',
        'old_price' => '',
        'badge' => 'Top',
        'rating' => '4.9',
        'blurb' => 'Estacion premium para cargar iPhone, Watch y AirPods con acabado de escritorio.',
        'description' => 'Una de las mejores opciones para clientes que quieren una base premium y orden visual en su setup.',
        'features' => ['Carga 3 en 1', 'Diseno premium', 'Ideal para escritorio o velador', 'Pensado para ecosistema Apple'],
        'art' => 'dock',
        'tone' => 'silver',
    ],
    [
        'sku' => 'belkin-usbc-cable',
        'brand' => 'belkin',
        'name' => 'Belkin Cable USB-C Trenzado',
        'image' => 'img/demo/brand-products/belkin/belkin-usbc-cable.svg',
        'price' => 'S/ 79',
        'old_price' => '',
        'badge' => '',
        'rating' => '4.8',
        'blurb' => 'Cable resistente para carga y sincronizacion diaria con mejor durabilidad.',
        'description' => 'Accesorio facil de vender porque resuelve desgaste diario, carga rapida y mejor vida util.',
        'features' => ['Cable trenzado', 'Mayor resistencia', 'Carga estable', 'Compatible con iPhone, iPad y Mac'],
        'art' => 'cable',
        'tone' => 'blue',
    ],
    [
        'sku' => 'belkin-dock-pro',
        'brand' => 'belkin',
        'name' => 'Belkin Dock Pro USB-C',
        'image' => 'img/demo/brand-products/belkin/belkin-dock-pro.svg',
        'price' => 'S/ 499',
        'old_price' => 'S/ 579',
        'badge' => 'Oferta',
        'rating' => '4.7',
        'blurb' => 'Dock para escritorio con conexiones utiles para MacBook e iPad.',
        'description' => 'Excelente complemento para productividad, ventas corporativas y clientes con setup de oficina.',
        'features' => ['Multiples puertos', 'Ideal para escritorio', 'Companero de MacBook', 'Acabado profesional'],
        'art' => 'dock',
        'tone' => 'dark',
    ],
    [
        'sku' => 'marshall-major-v',
        'brand' => 'marshall',
        'name' => 'Marshall Major V',
        'image' => 'img/demo/brand-products/marshall/marshall-major-v.svg',
        'price' => 'S/ 699',
        'old_price' => '',
        'badge' => 'Iconico',
        'rating' => '4.9',
        'blurb' => 'Audifonos con identidad muy marcada para quien quiere audio con estilo.',
        'description' => 'Marshall vende muy bien visualmente: su look clasico ayuda mucho en vitrinas y campañas con enfoque lifestyle.',
        'features' => ['Look iconico', 'Audio con caracter', 'Formato portable', 'Ideal para regalos premium'],
        'art' => 'headphones',
        'tone' => 'dark',
    ],
    [
        'sku' => 'marshall-emberton',
        'brand' => 'marshall',
        'name' => 'Marshall Emberton',
        'image' => 'img/demo/brand-products/marshall/marshall-emberton.svg',
        'price' => 'S/ 899',
        'old_price' => '',
        'badge' => '',
        'rating' => '4.8',
        'blurb' => 'Parlante compacto con mucha presencia visual y sonido energico.',
        'description' => 'Muy util para campañas de regalos, hogar y usuarios que quieren algo distinto a lo comun.',
        'features' => ['Parlante compacto premium', 'Diseno reconocible', 'Audio con pegada', 'Ideal para espacios personales'],
        'art' => 'speaker',
        'tone' => 'gold',
    ],
    [
        'sku' => 'marshall-woburn',
        'brand' => 'marshall',
        'name' => 'Marshall Woburn III',
        'image' => 'img/demo/brand-products/marshall/marshall-woburn.svg',
        'price' => 'S/ 2,299',
        'old_price' => '',
        'badge' => 'Premium',
        'rating' => '5.0',
        'blurb' => 'Parlante grande para salas y espacios donde el producto tambien decora.',
        'description' => 'Una pieza de audio premium con mucha presencia para clientes que buscan sonido y estilo en una sola compra.',
        'features' => ['Formato de sala', 'Look decorativo', 'Audio potente', 'Producto aspiracional'],
        'art' => 'soundbar',
        'tone' => 'dark',
    ],
    [
        'sku' => 'zagg-invisibleshield-xtr4',
        'brand' => 'zagg',
        'name' => 'Protector de Pantalla Zagg XTR4',
        'image' => 'img/demo/brand-products/zagg/zagg-invisibleshield-xtr4.svg',
        'price' => 'S/ 59',
        'old_price' => '',
        'badge' => 'Top',
        'rating' => '4.9',
        'blurb' => 'Protector premium para iPhone con enfoque en resistencia y claridad.',
        'description' => 'Muy facil de cruzar con ventas de iPhone, porque mejora la proteccion sin afectar la experiencia visual del equipo.',
        'features' => ['Mayor resistencia', 'Transparencia alta', 'Aplicacion precisa', 'Ideal para iPhone'],
        'art' => 'screen',
        'tone' => 'orange',
    ],
    [
        'sku' => 'zagg-keyboard-case',
        'brand' => 'zagg',
        'name' => 'Zagg Keyboard Case para iPad',
        'image' => 'img/demo/brand-products/zagg/zagg-keyboard-case.svg',
        'price' => 'S/ 329',
        'old_price' => '',
        'badge' => '',
        'rating' => '4.8',
        'blurb' => 'Funda con teclado para estudiar, escribir y aprovechar mejor el iPad.',
        'description' => 'Muy buena opcion para estudiantes, creadores y clientes que quieren productividad sin saltar a una laptop.',
        'features' => ['Teclado integrado', 'Proteccion completa', 'Ideal para estudio', 'Mejora la productividad'],
        'art' => 'keyboard-case',
        'tone' => 'blue',
    ],
    [
        'sku' => 'zagg-privacy-glass',
        'brand' => 'zagg',
        'name' => 'Zagg Privacy Glass',
        'image' => 'img/demo/brand-products/zagg/zagg-privacy-glass.svg',
        'price' => 'S/ 159',
        'old_price' => '',
        'badge' => 'Premium',
        'rating' => '4.7',
        'blurb' => 'Protector con privacidad para clientes que valoran discrecion y proteccion.',
        'description' => 'Pensado para usuarios corporativos, oficina y quienes quieren una capa extra de privacidad en pantalla.',
        'features' => ['Filtro de privacidad', 'Proteccion de pantalla', 'Pensado para oficina', 'Instalacion limpia'],
        'art' => 'screen',
        'tone' => 'dark',
    ],
];

function getBrandBySlug($slug, $brands)
{
    return $brands[$slug] ?? null;
}

function getProductsByBrand($slug, $products)
{
    return array_values(array_filter($products, function ($product) use ($slug) {
        return $product['brand'] === $slug;
    }));
}

function getProductBySku($sku, $products)
{
    foreach ($products as $product) {
        if ($product['sku'] === $sku) {
            return $product;
        }
    }
    return null;
}
